# Generated by Django 5.1.13 on 2025-10-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorreading',
            name='raw_value',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='voltage',
            field=models.FloatField(blank=True),
        ),
    ]
