# Generated by Django 5.1.13 on 2025-10-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_alter_sensorreading_raw_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorreading',
            name='raw_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='voltage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
