# Generated by Django 5.1.13 on 2025-10-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_device_measuring_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='measuring_time',
            field=models.IntegerField(default=15),
        ),
    ]
