# Generated by Django 5.1.13 on 2025-10-05 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_alter_device_measuring_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='measuring_time',
            new_name='reading_time',
        ),
    ]
