# Generated by Django 5.1.14 on 2025-11-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_rename_measuring_time_device_reading_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='max_value_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='device',
            name='min_value_limit',
            field=models.IntegerField(default=0),
        ),
    ]
