# Generated by Django 5.1.14 on 2025-11-11 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_alter_device_max_value_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='max_value_limit',
            field=models.IntegerField(max_length=9999),
        ),
        migrations.AlterField(
            model_name='device',
            name='min_value_limit',
            field=models.IntegerField(blank=True, max_length=9999),
        ),
    ]
