# Generated by Django 5.1.14 on 2025-11-11 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0010_alter_device_max_value_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='max_value_limit',
            field=models.IntegerField(),
        ),
    ]
