# Generated by Django 5.1.14 on 2025-11-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0011_alter_device_max_value_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='telegram_bot_token',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='device',
            name='telegram_user_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='min_value_limit',
            field=models.IntegerField(blank=True),
        ),
    ]
