# Generated by Django 5.1.14 on 2025-11-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0012_device_telegram_bot_token_device_telegram_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='reading_time',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='devicecommand',
            name='command_type',
            field=models.CharField(choices=[('clear_eeprom', 'Clear EEPROM'), ('restart', 'Restart Device'), ('enable_screen', 'Enable Screen'), ('disable_screen', 'Disable Screen'), ('update_api_url', 'Update API URL'), ('change_reading_time', 'Change Reading Time'), ('display_message', 'Display Message'), ('calibrate_sensor', 'Calibrate Sensor'), ('reboot', 'Reboot Device'), ('factory_reset', 'Factory Reset')], max_length=50),
        ),
    ]
