# Generated by Django 5.2.8 on 2026-01-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0014_alter_device_reading_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='token',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='devicecommand',
            name='command_type',
            field=models.CharField(choices=[('enable_screen', 'Enable Screen'), ('disable_screen', 'Disable Screen'), ('change_reading_time', 'Change Reading Time'), ('reboot', 'Reboot Device'), ('factory_reset', 'Factory Reset')], max_length=50),
        ),
    ]
