# Generated by Django 5.2.8 on 2026-01-15 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0015_device_token_alter_devicecommand_command_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='token',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
