# Generated by Django 5.2.8 on 2026-01-15 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0016_alter_device_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='token',
        ),
    ]
