# Generated by Django 5.1.14 on 2025-11-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_device_max_value_limit_device_min_value_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='max_value_limit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='device',
            name='min_value_limit',
            field=models.IntegerField(blank=True),
        ),
    ]
