# Generated by Django 5.1.14 on 2025-11-13 13:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0013_alter_device_reading_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='reading_time',
            field=models.IntegerField(default=15, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
